### PR TITLE
Fixes for deprecation warnings (numpy/scipy)

### PR DESCRIPTION
**Pull request by matbryan52**
Fixed while testing LT release 0.11. Passes the tests but haven't extensively checked, to finalise later.

## Contributor Checklist:

* [ ] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM-blobfinder/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [ ] I have added/updated test cases

### CODE REVIEW

**Comment by sk1p** [comment]
@uellue @matbryan52 we should merge this and release ASAP, as the latest `numpy` has removed `np.float` and friends completely, and with the latest compatible numpy release, on Python 3.11, this causes CI of LiberTEM to fail:

https://dev.azure.com/LiberTEM/57cdb6bb-8769-4b45-8e0b-13c01946a074/_apis/build/builds/2295/logs/122

**Comment by matbryan52** [comment]
> @uellue @matbryan52 we should merge this and release ASAP, as the latest `numpy` has removed `np.float` and friends completely, and with the latest compatible numpy release, on Python 3.11, this causes CI of LiberTEM to fail:
> 
> https://dev.azure.com/LiberTEM/57cdb6bb-8769-4b45-8e0b-13c01946a074/_apis/build/builds/2295/logs/122

Agreed, if we don't have much else to release could just be a point-release I suppose. One day I'd like to finish #40 but I'm not quite there yet.

**Comment by sk1p** [comment]
> Agreed, if we don't have much else to release could just be a point-release I suppose.

We can release it as 0.5, as there were a few features added, too: https://libertem.github.io/LiberTEM-blobfinder/changelog.html

May need a little work on the CI side, I'll open an issue to track this.

**Review by sk1p — APPROVED** [review]
LGTM!

**Pull request merged**
