### PR TITLE
Allow specifying per-frame coordinate offsets

### PR DESCRIPTION
**Pull request by uellue**
This helps to cope with a very large descan error and can improve fitting performance in a second pass if the first pass missed peaks.

## Contributor Checklist:

* [x] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/master/packaging/creators.json)
* [x] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM-blobfinder/tree/master/docs/source/changelog) for my contribution
* [x] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by uellue** [comment]
Re-test https://github.com/LiberTEM/LiberTEM/issues/679 on new OS X pipeline as soon as proper tests are implemented!

**Comment by uellue** [comment]
Creating a good example requires a suitable dataset, which we don't have yet as far as I know. For that reason I've opened #30 to add this later.

**Comment by uellue** [comment]
@sk1p Thank you for your review! The points should be addressed now. The docs-check fails since it requires PR #22 to be merged for the changelog.

**Review by sk1p — APPROVED** [review]
Looks good! Can you rebase this to fix the conflicts? Thanks!

**Comment by uellue** [comment]
> Looks good! Can you rebase this to fix the conflicts? Thanks!

Done! :-)

**Comment by sk1p** [comment]
> Done! :-)

Seems like a flake8 error found its way in there, once that is fixed I'll merge

**Comment by uellue** [comment]
Done! :-)

**Comment by sk1p** [comment]
Thx!

**Pull request merged**
