### PR TITLE
Sparse and GPU support for SparseCorrelationUDF

### PR DESCRIPTION
**Pull request by uellue**
This requires https://github.com/LiberTEM/LiberTEM/pull/1447

## Contributor Checklist:

* [x] I have added myself to [the creators.json file](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/master/packaging/creators.json)
* [ ] I have added [a changelog entry](https://github.com/LiberTEM/LiberTEM-blobfinder/tree/master/docs/source/changelog) for my contribution
* [ ] I have added/updated documentation for all user-facing changes
* [x] I have added/updated test cases

### CODE REVIEW

**Comment by sk1p** [comment]
Discussion with @uellue : pyfftw was removed as the still unresolved threading issues are making things hard to support.

> This requires https://github.com/LiberTEM/LiberTEM/pull/1447

Does that mean it's not backwards-compatible at all, or will it just not work with sparse data without said PR?

**Comment by sk1p** [comment]
CI failures are caused by [calling the `ltbc.zeros` function](https://github.com/LiberTEM/LiberTEM-blobfinder/blob/5791d295dfd09c1c41346f96540963a997a4401a/src/libertem_blobfinder/udf/correlation.py#L209) which was removed in this PR

**Comment by sk1p** [comment]
> This requires [LiberTEM/LiberTEM#1447](https://github.com/LiberTEM/LiberTEM/pull/1447)

Just as a reminder for ourselves, that means the dependency on the main LiberTEM Python package needs to be constrained to `>=0.12`, if we keep GCXS support a hard requirement. If we manage to "soften" the requirement (maybe via feature-detection of GCXS support in the mask container?), I think we only need v0.11 for general sparse processing, correct?

**Comment by sk1p** [comment]
I've rebased this and added the version constraint for LiberTEM>=0.12. If CI passes, this should be ready for review again - I did not yet test if this needs adjustments in combination with upsampling (probably?)

**Comment by matbryan52** [comment]
@uellue @sk1p I think this is good to go, I've added GPU for `fullframe`. The upsampling is fine because we cast to `numpy` before doing refinement, and I've added test parametrizations which cover this.

**Comment by sk1p** [comment]
> @uellue @sk1p I think this is good to go, I've added GPU for `fullframe`. The upsampling is fine because we cast to `numpy` before doing refinement, and I've added test parametrizations which cover this.

Thanks! I noticed one last issue: we are missing a dependency on `sparseconverter`. If we directly import a package, we should also depend on it - especially in case of this package, where, without any extras, `sparseconverter` won't be installed at all. I've pushed a fix for this.

I'll add CI for this situation separately.

Other than that, the PR should be good to go from my side, too!

**Review by uellue — COMMENTED** [review]
Looks good! Thank you for finishing this, I really appreciate it. 🙇‍♂️

**Pull request merged**
